### ISSUE TITLE
Migrate the application to ASP.NET Core MVC

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sample-app-net#13]
Target ASP.NET Core version: [2.1.0](https://blogs.msdn.microsoft.com/webdev/2018/05/30/asp-net-core-2-1-0-now-available/)

**Expected changes:**
- NuGet packages:
  - microsoft.* and system.* should be fine (they should have their .net standard alternative)
  - anglesharp supports netstandard = ok
  - kenticocloud.* supports netstandard = ok
  - jquery&bootstrap are not dependent on clr = ok
  - antlr is used by webgrease which is used by Microsoft.AspNet.Web.Optimization (for js/css bundling)...we can replace it with an analogical asp.net core package...see the docs
- [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration).
- take advantage of Dependency Injection to inject services like `DeliveryClient` into controllers.
- There may be some places where we can make use of the [view components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) and some other new ASP.NET Core functionality. 
- Changes in [multilingual support](https://andrewlock.net/url-culture-provider-using-middleware-as-mvc-filter-in-asp-net-core-1-1-0/)
- [`appveyor.yml`](https://github.com/Kentico/cloud-sample-app-net/blob/master/appveyor.yml) in case the build procedure needs some adjustments (e.g. change the platform)

**Workflow:**
- We won't merge it to `master` until it's done and thoroughly tested. 
- Before we merge the changes, we'll backup the original code in a separate branch. 

Feel free to refactor the code to use the latest standards.

Other things to consider during the conversion:
- See [ASP.NET Announcements](https://github.com/aspnet/Announcements/issues) to have more context about the changes in the new releases

**Comment by charithsoori** [comment]
@petrsvihlik This task is interesting. Are you expecting a single pull request? And also do you have a separate GitHub branch for this?

**Comment by petrsvihlik** [comment]
@charithsoori let me please check with my colleagues what the exact expectations are. i'll get back to you soon.

**Comment by petrsvihlik** [comment]
Good news @charithsoori ! You can start working on it :)

Regarding the workflow:
- I gave you write permissions to the repository which means that you can create own branch next to master and start pushing the code there. 
- We won't merge it to `master` until it's done and thoroughly tested. The code reviews and testing will be done by @JanLenoch who will also provide you with guidance and/or assistance if needed. (Just mention him in a comment and he'll get back to you asap.)
- Before we merge the changes, we'll backup the original code in a separate branch. (Will be done by @JanLenoch )
- I've also committed the [`appveyor.yml`](https://github.com/Kentico/cloud-sample-app-net/blob/master/appveyor.yml) file to the repository in case you need to adjust the build procedure (eg. remove vs 2015 builds as vs 2015 doesn't support asp.net core 2.0)

Some technical details regarding referenced NuGet packages:
- microsoft.* and system.* should be fine (they should have their .net standard alternative)
- anglesharp supports netstandard = ok
- kenticocloud.* supports netstandard = ok
- jquery&bootstrap are not dependent on clr = ok
- antlr is used by webgrease which is used by Microsoft.AspNet.Web.Optimization (for js/css bundling)...we can replace it with an analogical asp.net core package...see the [docs](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification)

Target ASP.NET Core version should be: 2.0 

I expect the biggest changes to be in the [configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration).
Also there may be some places where we can make use of the [view components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) and some other new ASP.NET Core functionality. Feel free to refactor the code to use the latest standards.
We should also take advantage of Dependency Injection to inject services like DeliveryClient into controllers.

**Comment by charithsoori** [comment]
Indeed a great news @petrsvihlik .
- The git-flow you suggested is very clean and ill send pull requests to migration branch from my fork.
- The initial technical spec is very clear.
Ill work start work on this.

**Comment by JanLenoch** [comment]
Hi @charithsoori ,

How is it going with the conversion? I was wondering if there's anything I could help you with. If so, just let me know.

Jan

**Comment by charithsoori** [comment]
Hi @janlenoch
Bit  away for a vacation these days and haven’t started the task yet . I’ll update you soon when I start the task.

**Comment by JanLenoch** [comment]
Cool, no pressure. If there's anything I can help with, just let me know.

**Comment by weng271190436** [comment]
Is .net core 2.1 still the target? 2.2 has been released.

**Comment by petrsvihlik** [comment]
Yeah, 2.2 is better, of course.

**Comment by petrsvihlik** [comment]
moved to: https://github.com/Kentico/delivery-sdk-net/issues/158
