### ISSUE TITLE
Secure Sections

### ISSUE THREAD

**Issue by VarinderS** [Kentico/cloud-sample-app-net#16]
Hope I'm not missing something obvious. 

What would be the general way to go about putting certain sections (received from kentico cloud) behind a login screen.

**Comment by petrsvihlik** [comment]
Well, typically you'd decorate the respective controllers with the [`[Authorize]`](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple) attribute, add one or more identity providers for authentication and implement a login page. 
The same as you would do for any other MVC application, no real difference there.

However, keep in mind that all content in the "Published" state is publicly available through the delivery API. So even if you put some sections on your website behind a login screen, an experienced user will be able to retrieve the content.

**Comment by VarinderS** [comment]
Hi Peter,

That makes sense - cheers

I'll close this thread
