### ISSUE TITLE
Help Rookies With App Settings

### ISSUE THREAD

**Issue by Steve-Fenton** [Kentico/cloud-sample-app-net#22]
Hello,

I followed the docs to set up the project against my sample account and added the three config items to the web.config.

I didn't spot that the Project ID was already at the bottom of the app settings, so the requests were being sent to the wrong account and authorization was failing with:

> The page cannot be displayed because an internal server error has occurred.

And under the hood:

>     Exception type: DeliveryException 
>     Exception message: Access token does not provide the permissions required for the project.

My suggestion is to move the existing ProjectId app setting up and separate it from the usual MVC app settings so people spot it and replace it - as having it last means it will win in situations where people add the app settings at the start of the app settings section.

Thanks,

Steve

**Comment by petrsvihlik** [comment]
This is primarily an opinion-based issue. Some people would be more likely to notice the key if it were in the top of the appSettings section, some would not. 

Anyway, we're preparing a brand new way of configuring the sample application which removes the need of editing the web.config entirely. (You can have a look in the [galleries_selfconfig](https://github.com/Kentico/cloud-sample-app-net/tree/galleries_selfconfig/DancingGoat) branch.) So I'm closing this issue now.

**Comment by petrsvihlik** [comment]
the auto-configuration has been merged...it should be now much easier for rookies to configure the app :)

**Comment by Steve-Fenton** [comment]
👍 I just tried it out - very simple.
