### ISSUE TITLE
Create a sample unit test for a controller

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sample-app-net#37]
# Motivation
We'd like to comp up with a best practice for testing apps running on .NET Delivery SDK for Kentico Cloud.

# Solution

- [ ] Add a new testing project (xunit) that will reference the [DancingGoat project](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/DancingGoat.csproj)
- [ ] Create an example unit test that would test controller by providing mocked responses as described  [here](https://github.com/Kentico/delivery-sdk-net/wiki/Faking-responses).

Originated from: https://github.com/Kentico/cloud-sample-app-net/issues/15#issuecomment-322185345

**Comment by JanLenoch** [comment]
Replaced by #76 .
