### ISSUE TITLE
Check for null parameters in LanguageClient

### ISSUE THREAD

**Issue by michalpaukert** [Kentico/cloud-sample-app-net#69]
Check for null parameters In [LanguageClient](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/Localization/LanguageClient.cs)
We should do it like it is implemented in method 
`public Task<DeliveryItemResponse<T>> GetItemAsync<T>(string codename, IEnumerable<IQueryParameter> parameters = null)`

**Comment by JanLenoch** [comment]
Replicating the same checks from the original `DeliveryClient` to the `LanguageClient` wouldn't give us the required quality guarantees. It would rather make sense to add a test project as per #76 .
